version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: skus
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
