sonar.projectKey=ribmarciojr_sku-view
sonar.organization=ribmarciojr

sonar.sources=skumanagement/api/v1/src,skuview/src
sonar.tests=skumanagement/api/v1/src/tests,skuview/src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/coverage/**,**/prisma/migrations/**

sonar.javascript.lcov.reportPaths=skumanagement/api/v1/coverage/lcov.info,skuview/coverage/lcov.info
sonar.coverage.exclusions=**/*.spec.*,**/*.test.*,**/tests/**

sonar.sourceEncoding=UTF-8
