FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --include=dev

COPY . .

RUN find src -name "*.js" -delete && \
    find src -name "*.js.map" -delete

RUN npx prisma generate --schema=./src/infra/prisma/schema.prisma

EXPOSE 3000